name: realized-library
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - numba
  - scipy
  - pandas
  - polars
  - pip
  - pip:
      - -e .
      - pytest
      - pytest-cov
